# Generated by Django 5.2 on 2025-04-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atom", models.CharField(max_length=2)),
                ("charge", models.SmallIntegerField()),
                ("isotope", models.CharField(blank=True, max_length=5)),
            ],
        ),
    ]
