# Generated by Django 5.2 on 2025-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="species",
            name="html",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="species",
            name="slug",
            field=models.CharField(default="", max_length=16),
            preserve_default=False,
        ),
    ]
