# Generated by Django 5.2 on 2025-05-04 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("atomic_number", models.PositiveSmallIntegerField()),
                ("symbol", models.CharField(max_length=2)),
                ("name", models.CharField(max_length=25)),
                (
                    "group",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(18),
                        ]
                    ),
                ),
            ],
        ),
    ]
