# Generated by Django 5.2 on 2025-05-04 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("periodic_table", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="group",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(18),
                ],
            ),
        ),
    ]
