# Generated by Django 5.2 on 2025-05-05 08:35

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("periodic_table", "0002_alter_element_group"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="element",
            managers=[
                ("category", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="element",
            name="link",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
