# Generated by Django 5.2 on 2025-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='metadata',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
